---
name: koillection

services:
  koillection:
    container_name: koillection
    image: koillection/koillection
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - volume_koillection:/uploads
    environment:
      TZ: "${DEVICE_TIMEZONE}"

  postgres:
    container_name: postgres
    image: postgres:16
    network_mode: host
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: "${DEVICE_TIMEZONE}"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - volume_postgres:/var/lib/postgresql/data

volumes:
  volume_koillection:
    external: true
  volume_postgres:
    external: true
