---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE
    - role: GITHUB.DOCKER.ROLE

  tasks:
    - include_vars: files/secret.yml
    - import_tasks: tasks/docker.yml
#    - import_tasks: tasks/dump.yml
#    - import_tasks: tasks/restore.yml

#localhost
#test_user
#test_db
#/var/lib/docker/volumes/volume_koillection/_data/
#/tmp/db.tar
#/tmp/images.tar
#files/backup/db.gpg
#files/backup/images.gpg
