---
- name: '-'
  hosts: all
  gather_facts: false
  become_method: sudo

  pre_tasks:
    - name: 'Connect to host & retrieve facts'
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'network'

  roles:
    - role: GITHUB.UPDATE.ROLE
    - role: GITHUB.DOCKER.ROLE

  tasks:
    - include_vars: files/secret.yml
    - import_tasks: tasks/docker.yml
#    - import_tasks: tasks/dump.yml
#    - import_tasks: tasks/restore.yml
